# This is for practise from coursera

## Numpy
1) This is numerical python module  
2) This is used to get solve all the numerical problem solved

## Use of numpy array

In [1]:
# creating an array and printing the values
import numpy as np
s =np.array([1,2,3,6,5,4,4])
print(type(s))
s.sort()
print(s)

<class 'numpy.ndarray'>
[1 2 3 4 4 5 6]


### NOTE:
1. **numpy.shape()**: returns the shape of the array in row and column form, if the column number is not same then it only returns the row number.
2. **numpy.reshape(arr_name,(row,col))**: this returns an array that is shaped as we have given in the argument. This doesn't effect the original array.
3. **numpy.flatten(array_name)**: this is used to convert multidimensional array to 1D array. It creates a copy of the orignal array.
4. **numpy.ravel(array_name)**: this is does also the same as above but it affects the orginal array.
5. **numpy.traspose(array_name)**: this is used to do the transpose of the 2D array. It don't work in 1D array case.
6. **numpy.concatenation((array_name1,array_name2...),axis=1)**: this is used to concat two or more arrays together. Axis is used if there is more than 1D array.By default axis value is 0.

In [21]:
n  =np.array([[1,2,1],[2,3,2]])
nn = np.array([[1,1,1],[2,2,2]])
print(n)
print(nn)
print("with axis 1\n",np.concatenate((n,nn),axis=1)) # this concats the array to the side of another array 
print("with axis 0\n",np.concatenate((n,nn),axis=0))# this concats the array to the below of another array


[[1 2 1]
 [2 3 2]]
[[1 1 1]
 [2 2 2]]
with axis 1
 [[1 2 1 1 1 1]
 [2 3 2 2 2 2]]
with axis 0
 [[1 2 1]
 [2 3 2]
 [1 1 1]
 [2 2 2]]


## use of np.zero and np.ones to generate zero and ones array

In [27]:
print(np.ones((2,3,3),dtype=np.int)) # first one gives the number of matrix needed

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [32]:
print(np.ones((3,2,2),dtype=np.int)) # next two tells the size of the matrix to be formed

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [33]:
print(np.ones((3,3,2),dtype=np.int)) # 2nd one tells the number of rows and 3rd one tells the number of column

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


### Use of identity and eye function
1. **We use identity(n)and np.eye(n,m,k)** : to create identity matrix of size in the argument... but in eye we can change the main diagnol of 1 by giving k a value +ve or -ve for up and down the diagnol of one.

In [36]:
#use of identity function
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
print(np.eye(4,4,-1))

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### Use of sum and prod

In [2]:
# we can use to sum the elements of the array and also find the product of the elements of the array using numpy
n,m=map(int,input().split())
arr = np.array([input().split() for _ in range(n)],int)
print(arr)
print(np.sum(arr,axis=0))
print(np.product(np.sum(arr,0),0))


2 2
1 2
3 4
[[1 2]
 [3 4]]
[4 6]
24


### Use of min and max 

In [10]:
# min(): returns the min value of the array along the axis given
arr # from the above cell
print(np.min(arr,0))
print(np.max(arr,0))
print(np.min(arr,1))
print(np.max(arr,1)) # 0- col wise, 1-row wise
# nothing given in the axis then returns the min or max value from the whole array

[1 2]
[3 4]
[1 3]
[2 4]


### Use of Mean,var,std : Mean, variance, std devatio
**NOTE: If the axis is not given in this then it finds the var,Mean,std of the flattend array**

In [14]:
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))

2.5
1.25
1.118033988749895


**NOTE**<br>
**1.We can use dot and cross to find the dot and cross product of two or more array**<br>
**2.We can use inner and outer function to find the inner and outer product of two or matrix**

## Use of numpy as np (few functions)

In [33]:
import numpy as np
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [35]:
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [50]:
o =np.linspace(0,4,9) # similar to arange function but it returns the how many number we want and split the number accordingly
print(o) # here we needed numbers between 0 to 4 and number of number we needed was 9
p = np.linspace(1,10,5)
print(p)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[ 1.    3.25  5.5   7.75 10.  ]


In [51]:
o.resize(3,3)
print(o)
p=np.resize(1,5)
print(p)


[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
[1 1 1 1 1]


# DATES and TIME

In [1]:
import datetime as dt
import time as tm

In [2]:
tm.time()

1590057532.5944328

In [9]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 5, 21, 16, 11, 12, 590776)

In [17]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2020, 5, 21, 16, 11, 12)

 we can use date time using pandas date time library

### Use of itertools.starmap()

In [23]:
from itertools import starmap
lis = [(2,3),(2,4),(3,2)]
print(starmap(pow,lis))
print(list(starmap(pow,lis)))

[8, 16, 9]



### List Comprehension and Lambda Functions

In [26]:
# Lambda functions are one line functions other than named functions this makes short functions
# This is to br noted that we have to evaluate only one expression in lambda
# we cant have default values in lambda and also we cant have comlex logic in labda functions 

In [29]:
myfunc= lambda a,b,c:a+b # the return of lambda is a function refrence therefore we need
# in the above expression shows that it takes 3 inputs and return the sum of the firs two variables
myfunc(1,2,4)

3

In [32]:
x= (lambda a,b,c: a+b+c)(2,3,4) # the last backet is the input of the values in the lambda functions
print(x)

9
