# NUMPY 

**Here we learn about the use of different functions in numerical library of python known as Numpy**

In [1]:
import numpy as np

## Creating Arrays

In [56]:
mylist=[1,2,3,4,5,6,7,8,9,0]
x=np.array(mylist)
print(x)
y=[1,2,3,4]
y=np.array(y)
print(y)

[1 2 3 4 5 6 7 8 9 0]
[1 2 3 4]


In [5]:
m = np.array([[7,8,9],[1,2,3],[4,5,6]])
m

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
m.shape

(3, 3)

In [9]:
n = np.arange(0,30,2) # to create an array with 2 steps
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
# if we want to change the size of the array we can use reshape array
n = n.reshape(3,5) # this creates a new array but not change the orignal array
# difference between reshape and resize
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [19]:
# we use linspace function as arange only but it returns number of elements as we want and split the interval accordingly
o = np.linspace(0,4,9) # from 0 to 4 we want 9 values
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [22]:
# we can use resize to change the dimension of the array
o.resize(3,3) # this changes the original array 
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [27]:
# numpy also has many short cuts to create an array
#creating the ones array
print(np.ones((3,2), dtype=int))
#creating the zeros array
print(np.zeros((3,2),dtype=int))

[[1 1]
 [1 1]
 [1 1]]
[[0 0]
 [0 0]
 [0 0]]


In [30]:
np.eye(3) # this creates an array with ones on diagonal and zeros on everwhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.diag(y) # this creates an diagonal array... works as eye but in place of one there are values of another list or array

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [36]:
# to repeate the elements in the array
np.array([1,2,3]*3)
# here the values of the array [1,2,3] are repeated 3 times

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [37]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

**NOTE:**  
The difference between the repeat and normal method is that repeat function repeates each value by the number given in the function whereas normal method repeated the whole array by the value given

In [39]:
p= np.ones((2,3),int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [44]:
np.vstack([p,p*2]) # here the values will be stacked in virtical position

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [46]:
np.hstack([p,p*2]) # here the values are stacked in horizontal manner

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [47]:
[p,p*2]

[array([[1, 1, 1],
        [1, 1, 1]]), array([[2, 2, 2],
        [2, 2, 2]])]

## Operations using numpy arrays

In [53]:
print(x)
print(y)
print(x[:4]*y)

[1 2 3 4 5 6 7 8 9 0]
[1, 2, 3, 4]
[ 1  4  9 16]


In [54]:
x[:4].dot(y)

30

In [57]:
z=np.array([y,y**2])
z

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [58]:
z.shape

(2, 4)

In [59]:
#we can take the traspose of the array using the T method
z.T

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [60]:
z.T.shape

(4, 2)

In [61]:
z.dtype

dtype('int32')

In [62]:
z=z.astype('f') # to change the data type of the array
z

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  9., 16.]], dtype=float32)

In [67]:
a=np.array([0,-1,-4,3,2,5,1])
print(a.argmax())
print(a.argmin())
# the above function gives the index of the max and min element in the array

5
2


## Indexing and Slicing in numpy arrays


In [71]:
s= np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [74]:
s[0],s[4],s[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [75]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [79]:
s[-4:] # from 4th last to end of the array

array([ 81, 100, 121, 144], dtype=int32)

In [80]:
s[-5::-2]
# important
# from last fifth to first with 2 step gap

array([64, 36, 16,  4,  0], dtype=int32)

In [85]:
r =np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [87]:
r[2,2] # value of the 2nd row and 2nd col

14

In [89]:
r[3,3:6] # from 3rd row all values from 3rd col to 5th col

array([21, 22, 23])

In [92]:
r[:2,:-1] # all rows till 1st and all col expect the last

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [96]:
r[-1,::2] # to select every second element from the last row

array([30, 32, 34])

In [99]:
r[r>22] # we can use this to have conditional indexing or values to return

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [100]:
r[r>30]=30 # here we take the elements that are greater than 30 and replace them with 30

In [101]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Copying data in Numpy

In [104]:
r2 =r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [106]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [109]:
r # here we see that the original array has been changed 
# therefore we have to be careful when we use numpy array

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [111]:
# if we dont want to change the values in the oringinal array we can use copy() 
r_copy=r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [114]:
r_copy[:]=10
print(r_copy)
print()
print(r)
# therefore we see that the original array is unchanged

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterating over array

In [118]:
test= np.random.randint(0,10,(4,3))
test

array([[9, 0, 7],
       [7, 1, 7],
       [8, 5, 4],
       [9, 0, 6]])

In [121]:
for r in test :
    print(r)

[9 0 7]
[7 1 7]
[8 5 4]
[9 0 6]


In [122]:
for i in range(len(test)):
    print(test[i])

[9 0 7]
[7 1 7]
[8 5 4]
[9 0 6]


In [123]:
# above are the two method to print the array or iterate the array
# but we can combine both the method in one by using enumerate function

In [125]:
#this method gives the row as well as the index of the row
for i, row in enumerate(test): # index as well as the row
    print("row",i,'is',row)

row 0 is [9 0 7]
row 1 is [7 1 7]
row 2 is [8 5 4]
row 3 is [9 0 6]


In [127]:
test2= test**2
test2

array([[81,  0, 49],
       [49,  1, 49],
       [64, 25, 16],
       [81,  0, 36]], dtype=int32)

In [129]:
# if we wish to iterate through both the arrays we can use zip
for i,j in zip(test,test2):
    print(i,j,i+j)

[9 0 7] [81  0 49] [90  0 56]
[7 1 7] [49  1 49] [56  2 56]
[8 5 4] [64 25 16] [72 30 20]
[9 0 6] [81  0 36] [90  0 42]
