# This is linear algebra functions and use
## Scalers and Vectors

Scaler = is a single number denoted as x <br>
Vector = is a series or list or array of scalers denoted by X <br>
* unlike list in python we in real life declare the dimension of the vector in row wise
* but in python we cant therefore we use the column wise method to represent the vector

In [22]:
import numpy as np

In [2]:
x1 = np.array([4,5,6])
print(x1)

[4 5 6]


In [3]:
print(x1.shape)

(3,)


In [4]:
x2 = np.array([[4],[5],[6],[8]])
print(x2)
print(x2.shape)
print(x2[0])
print(x2[0][0])

# if we want to resize or flatten it then we use the function resize
x2 = x2.reshape(-1,2) # we have used -1 bcoz we dont know the size of the array that y to reshape it we have used -1
print(x2)
print(x2.shape)

[[4]
 [5]
 [6]
 [8]]
(4, 1)
[4]
4
[[4 5]
 [6 8]]
(2, 2)


# Metrices and Tensors

### Tensor : 
is a generallization of array with more than two axis
* tensors are the genrealization of the array if the matrix has more than two dimensions
* we use them if we have to visualize more than two dimensions
* third dimension can be said as depth

In [9]:
# Here X is the 2x2 matrix 
X = np.array([[4,5,6],[7,8,9],[0,1,2]])
print(X.shape)
print(X)

print(X[1][1])
X[1:,:]=2
print(X)

(3, 3)
[[4 5 6]
 [7 8 9]
 [0 1 2]]
8
[[4 5 6]
 [2 2 2]
 [2 2 2]]


In [17]:
# Here is the use of Tensors
# this is used in nlp and deep learning alogirthms
# this is used to represent n dimension matrix
X  = np.array([[[4,5,6],[7,8,9]],
               [[1,3,4],[2,3,5]]
              ])
print(X)
print(X.shape)
# here the 3rd dimension is the depth of the matrix 

[[[4 5 6]
  [7 8 9]]

 [[1 3 4]
  [2 3 5]]]
(2, 2, 3)


(2,2,3) === has two rows with two as the depth and three is the number of elements inside it

# Transpose of a Matrix

* the row becomes the column and the column becomes the row of the matrix in 2D matrix

In [29]:
X = np.array([[1,2,6],
              [4,5,7]])
print(X)
xt = np.transpose(X)
print("this is the transpose of the matrix X")
print(xt)

[[1 2 6]
 [4 5 7]]
this is the transpose of the matrix X
[[1 4]
 [2 5]
 [6 7]]


In [30]:
X

array([[1, 2, 6],
       [4, 5, 7]])

In [32]:
y = X.reshape(-1,1)
print(y)
print(np.transpose(y))
print(y.shape)

[[1]
 [2]
 [6]
 [4]
 [5]
 [7]]
[[1 2 6 4 5 7]]
(6, 1)


# Broadcasting

* in this we can add the scaler to the vector and the numpy will add the scaler to each element of the vector or array
* similarly we can add the vactor to a matrix and the numpy will add the vector to each column of the matrix
* numpy allow us to do various operations on vactors and matrices

l = [[1,2,3,4],[4,5,6,7]] <br>
l = l+1 <br>
the above will not work as this is a list but the numpy array can help us to do the same thing and give the output

In [37]:
l= [1,2,3,4]
l = np.array(l)
print(l)
l = l**2
print(l)
print("the above is the square matrix")
l += 1
print (l)
print("the above matrix is the added one matrix to each element")

[1 2 3 4]
[ 1  4  9 16]
the above is the square matrix
[ 2  5 10 17]
the above matrix is the added one matrix to each element


### The above is the use of broadcasting 

# Matrix Multiplication

* one is the element wise multiplication 
* second is the matrix multiplication by the help of np.dot() function
## Element wise multiplication

In [40]:
X = [[1,2,3],[4,5,6],[7,8,9]]
y= np.eye(3) # this is the identityy matrix
print(X)
print(y)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
pro = X * y
print(pro)

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


### Above is the element matrix
* here each element is multiplied to the every corresponding element of the other matrix i.e. [00] with [00] of other matrix

In [49]:
X = np.array([[1,-3,4],[-2,10,-7],[0,1,0],[0,0,0]])
y = np.array([[5,0],[-2,11],[-3,12]])
prod = np.dot(X,y)
print(X)
print()
print(y)
print()
print(" the matrix multiplication of the two matrix is given below")
print()
print(prod)

[[ 1 -3  4]
 [-2 10 -7]
 [ 0  1  0]
 [ 0  0  0]]

[[ 5  0]
 [-2 11]
 [-3 12]]

 the matrix multiplication of the two matrix is given below

[[-1 15]
 [-9 26]
 [-2 11]
 [ 0  0]]


### Above is the matrix multiplication of the two matrix given

# Norms in a vector

* norm is the measure of the size of the vector

In [48]:
x = np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
l2 = np.linalg.norm(x)
print(l2)

6.0
